### ISSUE TITLE
evolution: annoying UI jump on page load

### ISSUE THREAD

**Issue by davidmurray** [chairemobilite/evolution#108]
This is caused by the 'Changer de personne' label changing to 'Chargement...' which has a smaller height

https://github.com/chairemobilite/evolution/assets/545502/4ec37aec-1dbf-4d04-bc24-4e511ad4f0a0

**Comment by davidmurray** [comment]
@kaligrafy  @tahini  selon vous, est-ce facile à régler?
Je trouve ça assez gossant comme petit mouvement haha

**Comment by kaligrafy** [comment]
Faudrait juste forcer la hauteur du div en css

**Comment by kaligrafy** [comment]
Tu peux faire un inspect sur le bouton changer de personnes et me donner les infos (class et/ou id du div)?

**Comment by davidmurray** [comment]
> Tu peux faire un inspect sur le bouton changer de personnes et me donner les infos (class et/ou id du div)?

```xml
<div class="center">
    <button type="button" class="survey-section__button button blue small">Changer de personne</button>
</div>
```

**Comment by kaligrafy** [comment]
OK, va falloir changer la classe. Je me mets ça assigné, mais je dois terminer d'autres choses avant

**Comment by davidmurray** [comment]
fixed by PR #160
