### ISSUE TITLE
Markers disappear when selecting a place on the map

### ISSUE THREAD

**Issue by davidmurray** [chairemobilite/evolution#121]
The markers disappear when selecting a place on the map:

https://github.com/chairemobilite/evolution/assets/545502/dc320428-a369-4a89-9ce8-4d451e0ba323

Not sure if this is intended or not, but this behaviour is a bit odd. If someone accidentally misclicks, the markers are gone and they must click "Chercher le lieu à partir du nom" again, which isn't intuitive.

@kaligrafy  was this intended?

**Comment by kaligrafy** [comment]
It was intended, but we may keep them until confirmed

**Comment by davidmurray** [comment]
Fixed
