### ISSUE TITLE
validations: allow to hide the interview list in validation portal

### ISSUE THREAD

**Issue by tahini** [chairemobilite/evolution#136]
It is possible to navigate through the interviews with the arrows at the top of the opened validation. The list takes a quarter of the page and could be hidden in those cases. There could be a simple collapse/expand button on the right, like many such interfaces

**Comment by millette** [comment]
![2023-08-24-111246_1920x2160_scrot-both](https://github.com/chairemobilite/evolution/assets/50741/96500603-7142-4f13-9538-1540bb8f8535)

Sauf quand l'écran est trop étroit, la liste tombe sous l'entrevue et là le bouton toggle est mal placé. Je vais corriger l'implémentation tout de suite.
