### ISSUE TITLE
validations: Add the possibility to discard individual trip diaries

### ISSUE THREAD

**Issue by tahini** [chairemobilite/evolution#137]
For those with access to od_mtl_2023: https://github.com/chairemobilite/od_mtl_2023/issues/366

To avoid discarding a complete interview because of one member with incomplete data, it should be possible to flag individual members to either keep or discard their diaries. See screenshot below:

![211914510-b4abfa8f-1fec-4c36-b162-de861877c0bb](https://github.com/chairemobilite/evolution/assets/4398897/86bc4e93-6672-40e6-a28d-d4322f675c6e)

**Comment by tahini** [comment]
@millette  est-ce que tu es sur cet issue?

**Comment by millette** [comment]
Je faisais #135 mais j'ai regardé un peu ceci vu l'urgence. Je peux switcher maintenant si on préfère.

**Comment by harcding** [comment]
Les deux sont égal. 135 (flagger pour 2e regard) peut servir à indiquer qu'il faut revenir pour marquer des CD comme poubelle.
Continue ce qui est plus plaisant, mais les deux haut en priorité. 
Merci

**Comment by millette** [comment]
Ça ressemble à ceci (en français: Garder, Écarter et Ignorer)

![2023-10-03-153006_887x981_scrot-crop](https://github.com/chairemobilite/evolution/assets/50741/b7797be8-a3e3-42d9-b93d-cff747c6096c)

**Comment by harcding** [comment]
Salut,

Super de voir de l'activité sur cette fonction. Comme décrit dans https://github.com/chairemobilite/od_mtl_2023/issues/366 en janvier passé, le statut IGNORE serait pertinent que si une personne saute la déclaration en ordre aléatoire et cherry pick les CD à rapporter. Je crois qu'il sera plus simple d'écrire un scripte post-validation pour voir si on doit ignorer des CD en fonction de l'ordre asssigné des CD (carnets-déplacements) et les infos fournies. 
*Pour le moment l'ordre d'assignation des personnes pour renseigner les CD n'apparait même pas dans le portail de validation, donc ça serait impossible pour les valideurs de savoir qui IGNORE. 

Donc dans le fond il n'y aurait **que les boutons KEEP et DISCARD à programmer**. 

Merci!

**Comment by millette** [comment]
Pour le statut IGNORE, je vais attendre le feedback de l'équipe mais c'est probablement un autre ticket à ouvrir.

@harcding 
Pour KEEP/DISCARD, il y a en fait un autre statut, INDÉTERMINÉ.

Dans l'interface, ça serait représenté par les boutons KEEP (fond vert s'il est sélectionné) et DISCARD (fond rouge) et aucun fond si le statut n'est pas sélectionné, c'est bien ça?

**Comment by harcding** [comment]
Super. Donc on pourrait sélectionner (mettre à vert ou rouge) et désélectionner (remettre à aucun fond).

**Comment by millette** [comment]
Voir #298

**Comment by tahini** [comment]
@harcding Comment devrait se comporter les données de la personne lorsque l'on sélectionner écarter? Est-ce que la personne devrait être automatiquement collapsée? Et si oui, les boutons devraient-ils rester visibles ou disparaître avec les infos? Il sera toujours possible de les ravoir en expandant la personne

**Comment by harcding** [comment]
Une fois qu'on sélectionne ÉCARTER/DISCARD, serait logique comme tu proposes de faire un collapse de toutes les informations associées au CD de cette personne et ne garder qu'une ligne avec P#, âge, genre. Nous permettra de 'keep track' à l'intérieur du ménage sans montrer trop de détails. 
Merci
