### ISSUE TITLE
Add the node 18 note about NODE_OPTIONS 

### ISSUE THREAD

**Issue by tahini** [chairemobilite/evolution#141]
In the Transition readme:

```
Note: If running with node version 18, webpack may return an error. In that case, run export NODE_OPTIONS=--openssl-legacy-provider before.
```

To add until we move to webpack 5

**Comment by millette** [comment]
Bonjour monde, je suis en standby, j'ai accès au code et issues - vous êtes très actifs, c'est beau à voir :-)

Certains des scripts dans les package.json (workspaces) utilisent déjà `cross-env NODE_OPTIONS=...` donc ça ne suffit pas d'ajouter un `NODE_OPTIONS=--openssl-legacy-provider` en lançant `yarn`, il faut possiblement ajouter `--openssl-legacy-provider` aux scripts existants sauf que node 16 va rejeter cette option et termine l'exécution immédiatement. Puisque [node 16 sera EOL en septembre](https://github.com/nodejs/Release#release-schedule), est-ce qu'on peut en même temps exiger node 18 pour le projet?

**Comment by kaligrafy** [comment]
Salut!

Il faut d'abord mettre à jour webpack vers version 5 et pour l'Instent, ça ne fonctionne pas automatiquement, et comme on entre en production bientôt, on attend la fin des enquêtes pour ne rien briser.

**Comment by millette** [comment]
D'ici à ce que webpack soit upgradé, et si on ne veut pas exiger node 18 tout de suite, je recommande de retirer NODE_OPTIONS qui est déjà utilisé pour l'option `--max_old_space_size=4096` dans les fichiers `survey/package.json` et `evolution/example/demo_survey/package.json`. Ensuite, on peut passer `NODE_OPTIONS=--max_old_space_size=4096` ou `NODE_OPTIONS=--max_old_space_size=4096 =--openssl-legacy-provider` selon qu'on utilise node 16 ou node 18.

J'ai utilisé <https://github.com/sharkdp/fd> pour trouver les _culprits_ avec:

```sh
fdfind package.json -x grep -H webpack|grep NODE_OPTIONS
```

à partir de mon clone de `od_mtl_2023`.

**Comment by tahini** [comment]
Not required anymore as node 16 support was dropped, the flag was added to all scripts
