### ISSUE TITLE
Map scrolls to problematic question when it should not

### ISSUE THREAD

**Issue by davidmurray** [chairemobilite/evolution#161]
Il y a un petit problème avec la fonctionnalité qui scroll à la question problématique quand on clique sur le bouton "continuer".

Voici l'enjeu:

On répond au questionnaire, mais en sautant certaines questions. Ces questions auront des erreurs
On clique sur le bouton 'sauvegarder et continuer en bas'
Section.componentDidUpdate est appelé et on trouve la première question problématique. Jusque là, tout va bien

Ensuite, si on décide de ne pas répondre à cette question problématique, mais plutôt changer la réponse à une autre question, un problème survient. Lorsque l'on change la réponse à une question du sondage, l'état valide/invalide de toute les questions est réinitialisé. ComponentDidUpdate est ensuite appelé. Problème: à ce moment, il semble que les éléments du DOM aient encore la classe question-invalid. Ainsi, dans componentDidUpdate, on scroll à une question qui était invalide, mais qui n'est plus affichée comme étant invalide. Comment faire en sorte que dans componentDidUpdate (ou autre fonction), on ait une version plus "à jour" des éléments du DOM? Peut-être que j'ai mal compris le flux d'information dans l'app et qu'il y a une manière plus simple de régler ça.

 
C'est peut-être pas trop clair, alors voici une vidéo:

https://github.com/chairemobilite/evolution/assets/545502/f7dfebf4-3d3c-4bc2-99d7-1ff87ba84f58
 

Code : https://github.com/chairemobilite/evolution/blob/3939b2b0e2f4ae8a1b9c7b1e7115e66436453c7f/packages/evolution-legacy/src/components/survey/Section.js#L58-L77

**Comment by kaligrafy** [comment]
Pour que le premier champ erroné soit activé automatiquement, il faut que le props submitted soit vrai. Et pour qu'il soit vrai, il faut que le call à updateInterview soit _all, ce qui arrive quand on clique sur le bouton confirmer. Pourtant, le props submitted reste vrai aussi la première fois qu'on change un champ après avoir cliqué sur confirmer. Par la suite, il se désactive et le bogue n'est plus là. Donc pourquoi submitted reste vrai la première fois puis se fixe par la suite: mystère. Je cherche.

**Comment by kaligrafy** [comment]
Il y a un render qui se fait avant l'envoi des données au serveur lors de la modification du premier champ, alors submitted reste true. il faudrait détecter que ce render n'est pas un envoi au serveur.

**Comment by kaligrafy** [comment]
Il faut jsute vérifier que le loading state est bien à 0. Le fait de changer le loading state avant l'update de l'interview faisait que le submitted était encore true.

**Comment by kaligrafy** [comment]
@davidmurray Pourrais-tu vérifier si le PR #199 fixe le problème sans en ajouter des nouveaux?
