### ISSUE TITLE
Drop node 16 support

### ISSUE THREAD

**Issue by tahini** [chairemobilite/evolution#165]
If we drop node 16, we can update the build scripts with the `--openssl-legacy-provider` flag to support node 18+ without having to upgrade to webpack 5 just yet.

Node 16 end of life is set for september 11.

Any objection? 
cc @greenscientist @davidmurray @kaligrafy @vincentchab @Frost000 @samuel-duhaime @XavierKMT

**Comment by davidmurray** [comment]
no objection here!

**Comment by greenscientist** [comment]
Do we need to do the change in transition also?

**Comment by tahini** [comment]
eventually too, but it's not a requirement for this one (I think)

**Comment by samuel-duhaime** [comment]
No objection! Let's do this!
