### ISSUE TITLE
On windows, yarn format does not work.

### ISSUE THREAD

**Issue by Frost000** [chairemobilite/evolution#196]
The script can run and indicates errors but does not correct them

**Comment by samuel-duhaime** [comment]
Salut, j'ai testé de mon bord "yarn format" dans evolution\packages\evolution-frontend\package.json. Puis, j'ai réussit à le faire fonctionner correctement en ajoutant une nouvelle commande avec "yarn format:windows", car $PWD ne fonctionne pas avec windows. Donc, je pense qu'il va falloir changer le yarn format de tous les package.json.

Voici l'exemple du changement dans evolution\packages\evolution-frontend\package.json
```
"format": "prettier-eslint $PWD/'src/**/*.{ts,tsx}' --write",
"format:windows": "prettier-eslint ./src/**/*.{ts,tsx} --write"
```

Puis, dans evolution\package.json, on peut faire quelque chose comme:
```
"format": "yarn workspace evolution-common run format && yarn workspace evolution-backend run format && yarn workspace evolution-frontend run format",
"format:windows": "yarn workspace evolution-common run format:windows && yarn workspace evolution-backend run format:windows && yarn workspace evolution-frontend run format:windows",
```

Je crois qu'avec ses changements, ça devrait fonctionner avec windows maintenant.

**Comment by kaligrafy** [comment]
Est-ce possible de proposer un PR pour ça?
