### ISSUE TITLE
validations: Filters are reset when hiding/showing the interview list

### ISSUE THREAD

**Issue by tahini** [chairemobilite/evolution#243]
From https://github.com/chairemobilite/od_mtl_2023/issues/1118

"The filters and settings stay the same IF I don't click the hide folder button, but reset when I click the hide/show folder button. So a more clear issue."

The filters on top of the interview list seem to be reset upon showing/hiding.

cc @millette

**Comment by tahini** [comment]
@millette unless this was fixed in your last PR? I just noticed our surveys don't have this commit yet...

**Comment by millette** [comment]
@tahini Avec https://github.com/chairemobilite/evolution/pull/233/commits/bab3b375c4cb5cbf13431db08fa61ee8c8c69b75 c'est réparé, la liste reste dans le dom (ça toggle un ```display: none``` maintenant).

**Comment by tahini** [comment]
En effet, fixé par le commit mentionné
