### ISSUE TITLE
validations: Add possibility to collapse individual persons

### ISSUE THREAD

**Issue by tahini** [chairemobilite/evolution#283]
In the summary one pager, it should be possible to collapse/expand each individual person

**Comment by mathildemoliner** [comment]
Est-ce qu'il y a un délai avant que ce soit sur test2 ? 
Le commit date d'il y a 4 jours et je ne vois pas le collapse 
![image](https://github.com/chairemobilite/evolution/assets/54894778/813bc0ab-2a65-43f1-a6ae-c9797efa3a02)

**Comment by tahini** [comment]
Pour que ce soit dans evolution, il faut mettre à jour la plateforme dans od_mtl_2023 (ça ne se fait pas automatiquement). On vient de le faire, la prochaine mise à jour (demain ou plus tard aujourd'hui si on fait le release hebdo cet après-midi)

**Comment by mathildemoliner** [comment]
Super merci pour la clarification !
