### ISSUE TITLE
accessibility: make sure the slider widget is accessible

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/evolution#38]
Replace by radio buttons or drop-down menu with labels values and maybe add more precise half values.

**Comment by tahini** [comment]
@kaligrafy Will there be sliders in EOD2023? If not, I'll remove from current milestone

**Comment by kaligrafy** [comment]
There may be if we include respondent behaviour questions at the end (length of survey, burden, etc.) Catherine and Hubert wants them (I do too), so I would keep them. And we use them in almost every other surveys
