### ISSUE TITLE
evolution: Avoid centering text on main page

### ISSUE THREAD

**Issue by davidmurray** [chairemobilite/evolution#39]
Hi,

I believe that left-aligned text looks more professional. Comparison:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/545502/191142200-5228f52b-5d99-4c31-a871-77fba09b0bfd.png"> 
<img width="300" alt="image" src="https://user-images.githubusercontent.com/545502/191142247-998290a3-1a67-4beb-afa5-963d12f7374e.png">

Thanks.
David

**Comment by tahini** [comment]
In fact, the center styles comes from the locale string in `survey.json`. It is not part of the HomePage. Simply update the locale string in the project itself
