### ISSUE TITLE
evolution: Find a solution to keep track of users who edited an interview

### ISSUE THREAD

**Issue by tahini** [chairemobilite/evolution#43]
The quick&easy solution is to add a field in responses with an array of user ids who edited the interview. But this exposes the IDs of users with higher privileges than participants. That is not good. It should be handled only server side and never make it to the client.

**Comment by tahini** [comment]
Part of the participant/user split

**Comment by tahini** [comment]
Here's a proposal for this one: 

* Add a table to the database, with 4 fields: user_id, interview_id, opened_at, last_update. The last 2 fields are timestamps.
* `opened_at` would be set upon activation of the interview
* `updated_at` or `last_update` would be set at every update, to the most recent entry per user_id/interview_id
* Those update can be done through a request middleware on the activeInterview and updateInterview express routes. That middleware would be optional (defaults to a function that simply passes through), and present only on the admin side.

We could also add a fifth column: for_validation (boolean), which would be `true` if the interview was opened by a user for validation, and `false` if for edition. PK would be user_id, interview_id, for_validation

**Note** The optional middleware mechanism can also be used for logging purpuses (#47), which would decouple the interview from the logic of logging, which are totally unrelated.

**Comment by kaligrafy** [comment]
We should use updated_at to be consistent with other updated_at fields elsewhere in evolution and transition

**Comment by kaligrafy** [comment]
maybe replace opened_at by viewed_at
