### ISSUE TITLE
Generator: None choices are generated in some cases

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/evolution#437]
in common/choices.tsx:

export const None: Choices = [...]

We should find why this is generated and remove it altogether.

**Comment by tahini** [comment]
Is it possible to give some more explicit example? Which survey, which section, in which file?

**Comment by kaligrafy** [comment]
Fixed in next PR by force-deleting 5 empty lines in the choices tab in the excel file.

**Comment by tahini** [comment]
So it is empty lines at the end of a sheet. We need to make sure that every field we use is defined
