### ISSUE TITLE
error management: If an error occurred, we are redirected to maintenance page

### ISSUE THREAD

**Issue by tahini** [chairemobilite/evolution#457]
This is confusing.

Many cases can redirect to the page:
* Unauthorized (if the user has been logged out for some reason) (maybe not, I'm not sure about this one)
* A server error returned by the query to server
* A shitty connection (no response from server)

The user should be redirected to a more "interesting" and "pretty" page, saying something like "Oops something went wrong, you may try again (link to the suryve), if the problem persist, please contact [whoever needs to be contacted for this survey], make sure you have a trustable internet connection"

@greenscientist  @kaligrafy any suggestion for the text to show? screenshot from a Oops page you like?

**Comment by tahini** [comment]
Interesting read on error messages: https://uxwritinghub.com/error-message-examples/

des phrases de 8 mots et moins...

**Comment by tahini** [comment]
Voici la nouvelle page proposée. Chaque texte peut être overridé au niveau des enquêtes (genre pour donner les coordonnées des administrateurs). ça vous irait? @greenscientist  @kaligrafy 

![Capture d’écran du 2024-04-30 12-04-20](https://github.com/chairemobilite/evolution/assets/4398897/cafadfd9-9777-41b6-8d5b-82a4225a6c5d)

**Comment by kaligrafy** [comment]
Go!

**Comment by greenscientist** [comment]
Ca prendrait peut-etre un lien "contact générique" qu'on peut avoir sans devoir l'écrire manuellement à chaque fois.

**Comment by tahini** [comment]
Il faudrait idéalement configurer un courriel dans chaque instance, genre dans la config, et l'inscrire ici. C'est un autre issue!
