### ISSUE TITLE
Add "Not applicable" for the user for range input

### ISSUE THREAD

**Issue by samuel-duhaime** [chairemobilite/evolution#539]
# Issue

## Justification
In some of our surveys, we often ask radio input questions that are not applicable to the user. As a result, the user doesn't know how to respond in this situation.

## Description
The user should be able to click on 'not applicable'. We should add a parameter to the widget (notApplicable: boolean). 

## Screenshot
We could do something like this.

![image](https://github.com/chairemobilite/od_mj_2023/assets/78976679/d9deff89-f501-4d7b-a33b-c6cd51d3b929)

**Comment by tahini** [comment]
@kaligrafy As-tu une idée/opinion là-dessus? On ajoute un checkbox qui donnerait une valeur de quoi exactement? J'imagine qu'on ne veut pas mélanger des strings et des chiffres. Et si le checkbox est coché, on disable le slider?

**Comment by kaligrafy** [comment]
Super complexe... Ça va prendre un checkbox genre à droite du slider ou en-dessous qui dit Ne s'applique pas à ma situation" par exemple

**Comment by tahini** [comment]
En passant, je suppose que le titre devrait bien être range input et non radio input?

**Comment by tahini** [comment]
Voici de quoi ça peut avoir l'air. ça semble fonctionner...

![Capture d’écran du 2024-06-17 17-15-31](https://github.com/chairemobilite/evolution/assets/4398897/65777900-168b-4180-8599-876ad0ff2f86)

**Comment by samuel-duhaime** [comment]
> En passant, je suppose que le titre devrait bien être range input et non radio input?

Oui, en effet. C'est corrigé.
