### ISSUE TITLE
Refactor: Migrate survey.json to survey.yaml 

### ISSUE THREAD

**Issue by samuel-duhaime** [chairemobilite/evolution#614]
# Issue

## Justification
It's difficult and troublesome to update and review the introduction in survey.json homepage object. Let's transfer that to a file that is easier to read, especially for a long paragraph.

## Description
Migrate survey.json to survey.yaml

**Comment by tahini** [comment]
The translation file resides in the survey projects, each project must/should invidually move to .yaml. There's nothing to do in Evolution, we already support yml translation files.

**Comment by samuel-duhaime** [comment]
> The translation file resides in the survey projects, each project must/should invidually move to .yaml. There's nothing to do in Evolution, we already support yml translation files.

@tahini 
You mean we can migrate survey.json to survey.yaml without changing anything in Evolution? I would have done it that way earlier if I had known.
