### ISSUE TITLE
inputMap: Presser le bouton "Search Location" trop vite fait un message d'erreur.

### ISSUE THREAD

**Issue by tahini** [chairemobilite/evolution#621]
Dans les pages avec un widget google maps, si on presse le bouton "Search Location" avant que le service google maps soit completement chargé, la location n'est pas trouvée et on a un message d'erreur. Il faudrait faire en sorte que le bouton n'aparraisse pas ou ne soit pas cliquables avant le chargement complet.
![image](https://github.com/user-attachments/assets/0cce9e12-82ba-4e34-8be9-00a722315fc9)
![image](https://github.com/user-attachments/assets/4c6b0830-b383-4ead-ade5-6bce1d2bcc2e)

**Comment by samuel-duhaime** [comment]
J'ai mis à medium priority, parce que ça fait quand même en sorte, que les tests ne fonctionnent pas parfois (sur mon desktop à la maison et l'ordinateur de Gabriel.)

**Comment by samuel-duhaime** [comment]
Je mets à high priority, ça a l'air que tous les ordis moindrement puissants font ce problème. Ça ralentit quand même fortement le workflow si on ne peut pas tester en local.
