### ISSUE TITLE
mapFindPlace: Zoom when results are found

### ISSUE THREAD

**Issue by tahini** [chairemobilite/evolution#665]
The map widget may have a high default zoom, but it should zoom in when a search returns results. If the results are for an area larger than the current area, the bounding box is updated, but if it is smaller, it should also zoom in, or at least have a minimum zoom small enough to really see where the point is.

For example, od_nationale, longue distance and MJ have a default zoom of 8 or 9, but we should zoom in when home location is found.

**Comment by tahini** [comment]
En fait, le "problème" qu'on veut régler c'est que le zoom par défaut de la carte, sans config, est très élevé (16) et correspond à un niveau où un simple clic est acceptable. Et c'est surtout centré par défaut sur un endroit arbitraire (sans recherche préalable, ni lien avec ce que le participant a entré) correspondant à la configuration du centre de la carte.

Voici une proposition pour solutionner ce problème:

1- Mettre le zoom par défaut (hors config) supérieur au niveau acceptable (qui est de 14 je crois?), obligeant ainsi le participant à au moins faire un effort autre que juste cliquer n'importe où sur la carte si pas de résultat

2- La fonction `queryString` pourrait retourner soit une `string`, soit un array d'objets avec une `queryString` et un `zoom`, par ordre de priorité, où le zoom correspond au niveau désiré si des résultats sont montrés avec cette requête. Par exemple, la première requête pourrait être l'adresse, avec un niveau de zoom de 16. S'il n'y a pas de résultats, la requête suivante serait sur la ville, avec un zoom plus élevé, puis le province, avec un zoom encore plus élevé. Ces valeurs seraient configurable par enquête.

**Comment by samuel-duhaime** [comment]
Peux-tu expliquer cette partie ? Quand est-ce qu'il y a plusieurs requêtes ?

> La fonction queryString pourrait retourner soit une string, soit un array d'objets avec une queryString et un zoom, par ordre de priorité, où le zoom correspond au niveau désiré si des résultats sont montrés avec cette requête. Par exemple, la première requête pourrait être l'adresse, avec un niveau de zoom de 16. S'il n'y a pas de résultats, la requête suivante serait sur la ville, avec un zoom plus élevé, puis le province, avec un zoom encore plus élevé. Ces valeurs seraient configurable par enquête.
