### ISSUE TITLE
Support i18next translations for labels in survey projects

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/evolution#77]
Example: for telephonic interviewers, we must have differente labels for questions and/or response choices. I suggest implementing nested languages for that and setting the default language for interviewer to this version. It could also serve for locales like fr_CA, fr_FR, etc.
For interviewers, it would be fr_LONG or fr_INTERVIEWER.

**Comment by tahini** [comment]
After reading i18next documentation, there's a feature called 'context', which allows to suffix translation key with the context name. For example key_male, key_female, key_interviewer, key_interviewer_female.

In a locale file, we would have 
```
{
 "key": "translation 1",
 "key_male": "Translation for a man",
 "key_female": "Translation for a woman",
}
```
Then, calling `t('key', { context: 'female' })` would use the key_female key. Any unknown context would fallback to the original key without suffix.

There's also a count feature, where keys suffixed with a number can be used if the 'count' option is set.

To make that user friendly to edit, the "i18n ally" extension of VS code make it much easier to track translations and edit them directly in the code, or in a panel. See the below screenshot for an example. Labels would now all be functions that receive a TFunction in parameter, along with the interview, path and user.

![Capture d’écran du 2023-05-04 14-20-11](https://user-images.githubusercontent.com/4398897/236294346-309e6418-5660-4208-96fc-1aeeb5e233d3.png)

This is a possibility.

Still to be determined if the interviewer should be a context or a whole different set of file (I'll have to figure out if we can duplicate the keys in many files with the extension).

@kaligrafy @greenscientist how does that sound to you?

**Comment by greenscientist** [comment]
Could work. Still a bit feeling like we are circumventing a mecanism for a different purpose, but it's much better than having a different langage.

**Comment by tahini** [comment]
> Could work. Still a bit feeling like we are circumventing a mecanism for a different purpose, but it's much better than having a different langage.

I don't think we are... I think the context thing is exactly for this purpose... Combine that with a react context for the interviewer and we're in the i18n business!

See the documentation video linked to by https://www.i18next.com/translation-function/context The context is cake and muffin!

**Comment by greenscientist** [comment]
I would still try to limit the usage of this context to only interview questions. Not any other part of the UI where it should be explicit that's it's accessed by an interviewer.

**Comment by tahini** [comment]
I'm not sure I see your objection here. Of course the context would be used only when/if necessary, that is, for interview questions and widgets (at least that is where we would inject the interviewer-specific context, context itself is an i18next feature anyway)

**Comment by greenscientist** [comment]
It could be tempting to use this interviewer context for like the main page of an interviewer. But we should not. And it should not be possible to do so that people do not make mistake when write the translation file.

**Comment by tahini** [comment]
Yes, with i18next, in the options, you can add any field, then use {{field}} in the translated text

**Comment by tahini** [comment]
So, to summarize, here's what I'd propose for our labels to fully support i18next translations, with all its features like context and plural support, etc:

**Current**

Labels, and everything that is translatable currently, are of type `string | LangData<CustomSurvey, CustomHousehold, CustomHome, CustomPerson>` where `LangData` is defined as follows:

```
type LangData<CustomSurvey, CustomHousehold, CustomHome, CustomPerson> = {
    [lang: string]: string | ParsingFunction<string, CustomSurvey, CustomHousehold, CustomHome, CustomPerson>;
};
```
With `ParsingFunction` being:

```
type ParsingFunction<T, CustomSurvey, CustomHousehold, CustomHome, CustomPerson> = (
    interview: UserInterviewAttributes<CustomSurvey, CustomHousehold, CustomHome, CustomPerson>,
    path: string,
    user?: CliUser
) => T;
```

**Proposal**

We could add a translation function as follows

```
type TranslatableFunction<CustomSurvey, CustomHousehold, CustomHome, CustomPerson> = (
    t: TFunction,
    opts: TOptionsBase,
    interview: UserInterviewAttributes<CustomSurvey, CustomHousehold, CustomHome, CustomPerson>,
    path: string,
    user?: CliUser
) => string;
```

So our labels types would now be `string | LangData<CustomSurvey, CustomHousehold, CustomHome, CustomPerson> | TranslatableFunction<CustomerSurvey, CustomHousehold, CustomHome, CustomPerson>`

The type would be more complicated, so we would need a centralized function somewhere that will handle the label resolution, that all components using the labels can call. That function will need to receive the `t` function in parameters and should handle getting the proper context from ... the universe (exact way TBD) ... 

For how to use this new type, see the example in a previous comment. The i18n Ally extension will help managing the labels.
