### ISSUE TITLE
demo_survey: section not marked as completed in the SectionNav

### ISSUE THREAD

**Issue by tahini** [chairemobilite/evolution#787]
When the SectionNav component was moved to typescript, the previous section completion status was modified for this: `!!completedStatusBySectionShortname[previousSection]`. But when the previous Section is hidden in nav, it does not have a completion status so this becomes false instead of `undefined` effectively marking the section as disabled forever and ever.

This cause the unit tests to fail.

While investigating this, we observe that `hiddenInNav: true` is always accompanied by a `parentSection` property to specify, essentially making it a sub-section of the parent section. Should we force this in the type, making the presence of the parentSection property synonym of `hiddenInNav` and remove this last property?

**Comment by samuel-duhaime** [comment]
@tahini  Yes, we can do that. I have no objections.

> While investigating this, we observe that `hiddenInNav: true` is always accompanied by a `parentSection` property to specify, essentially making it a sub-section of the parent section. Should we force this in the type, making the presence of the parentSection property synonym of `hiddenInNav` and remove this last property?
