### ISSUE TITLE
generator: Generate the example widget/config survey in the CI

### ISSUE THREAD

**Issue by tahini** [chairemobilite/evolution#795]
With #794 we have a working generator project (ie it produces compilable code, even though the project itself is not complete and has no actual frontend or backend application).

To make sure updates in evolution do not break the generated code, it should be run during CI. Here are the steps to run the generator:

* Run in an environment with python enabled and poetry (see https://github.com/chairemobilite/evolution/tree/main/packages/evolution-generator#how-to-run step 1 for instructions to install poetry if necessary)
* Install the poetry dependencies from the `packages/evolution-generator` directory: `cd packages/evolution-generator && poetry install`

Now, from the root of the project:

* Run the generator: `yarn generateSurvey:example`
* Make sure the evolution code is compiled before hand: `yarn compile`
* Compile the generated code: `yarn workspace demo_generator run compile:example`

**Comment by greenscientist** [comment]
Ok, I'll check that once #794 is merged
