### ISSUE TITLE
Radio button labels do not render HTML

### ISSUE THREAD

**Issue by davidmurray** [chairemobilite/evolution#95]
Example question:
```js
export const personDeparturePlaceIsHomeConfirm = {
    type: "question",
    path: "example",
    inputType: "radio",
    datatype: "string",
    twoColumns: false,
    containsHtml: true,
    label: {
        fr: 'Test',
        en: 'Test',
    },
    choices: [{
            value: "test",
            label: {
                fr: `<span class='_strong'>bold</span> not bold`,
                en: "<span class='_strong'>bold</span>",
            }
        },
    ]
};
```

Example question that is not rendering correctly (question #41e in od 2023 mtl): 
![image](https://github.com/chairemobilite/evolution/assets/545502/e17c127e-83ce-45eb-98ef-f63b5976147e)

**Comment by tahini** [comment]
Search for `dangerouslySetInnerHTML`. There are example in SimpleModal and InputMapFindPlace. This will need unit tests as well. And it should be supported for InputRadio, and InputCheckbox.
